spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://salesexpense.cyxxbdqenh5e.ap-southeast-1.rds.amazonaws.com:3306/salesexpense?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: gatpsolutions
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
     hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
     jdbc:
        lob:
        non_contextual_creation: true 
  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 25MB