atm.withdrawal: WITHDRWL
ignored.words:
  - for
  - from
  - there
  - their
  - then
  - and
  - then
  - boston
  - bar
  - bost
  - pot
  - the
  - cha
  - burger
  - pizza
account.list:
  - bank
  - creditcard